In [1]:
import numpy as np
import pandas as pd

In [2]:
input_sets = np.array([ [0.05, 0.10]])

labels = np.array([[ 0.01 , 0.99]])

n = len(labels)

In [3]:
np.random.seed(42)
weights = np.array([[0.15,0.20],[0.25,0.30]])
bias =np.array([1.35])
lr = 0.05
print(weights)
labels[0][1]

[[0.15 0.2 ]
 [0.25 0.3 ]]


0.99

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivation(x):
    return sigmoid(x)*(1-sigmoid(x))

In [5]:
input = input_sets

#forward propagation
xw = np.dot(input, weights)+bias
z = sigmoid(xw)
error = 1/2*(labels-z)*(labels-z)

#backward propagation
dcost =labels-z#  d(error)/d(outo2)
dpred = sigmoid_derivation(z) #  d(out02)/d(neto2)
z_del = dcost * dpred

#updating the weights
input = input_sets.T
derivation = np.dot(input , z_del) #d(error)/d(weight)
weights = weights-lr*derivation

In [6]:
error

array([[0.31157003, 0.01793765]])

In [8]:
weights

array([[0.15042224, 0.19989873],
       [0.25084449, 0.29979746]])

In [9]:
for epoch in range(25000):
    input = input_sets
    xw = np.dot(input, weights)+bias
    z = sigmoid(xw)
    error = 1/2*(labels-z)*(labels-z)
    dcost = labels-z
    dpred = sigmoid_derivation(z)
    z_del = dcost * dpred
    input = input_sets.T
    weights = weights-lr*np.dot(input , z_del)

In [10]:
error

array([[0.47670172, 0.0690581 ]])

In [11]:
weights

array([[11.76355511, -3.42983732],
       [23.47711021, -6.95967464]])